### ISSUE TITLE
Parse error when dividing by 0 in task4

### ISSUE THREAD

**Issue by SUIFENGSK** [team-checkr/fsharp-starter#8]
When we try to input the following program to Inspectify, it will cause a parse error
```
{true} a:=1/0 {true}
```
![01](https://user-images.githubusercontent.com/55560661/228223063-5143de18-482d-49ad-9a60-75fd5de1fba9.png)
Error message:
```
Parse failed at line 0, column 11:
Last token: 
Unhandled exception. System.Exception: Failed to parse.

Did you remember to surround your program with predicate blocks, like so?

  { true } skip { true }

Predicate.Parse+ParseError: ParseError
  ({ pos_fname = ""
     pos_lnum = 0
     pos_bol = 0
     pos_cnum = 11 }, "",
   System.Exception: unrecognized input
   at FSharp.Text.Lexing.LexBuffer`1.EndOfScan()
   at FSharp.Text.Lexing.UnicodeTables.scanUntilSentinel(LexBuffer`1 lexBuffer, Int32 state)
   at Predicate.Lexer.tokenize(LexBuffer`1 lexbuf) in D:\OneDrive_Privat\OneDrive\Uni_DTU\4.semester\02141 Datalogisk modellering F23\02141_workspace\02141-group-21-ef0e8\predicates\Lexer.fs:line 229
   at Predicate.Parse.parser@11-1.Invoke(LexBuffer`1 lexbuf)
   at FSharp.Text.Parsing.Implementation.interpret[tok,a](Tables`1 tables, FSharpFunc`2 lexer, LexBuffer`1 lexbuf, Int32 initialState)
   at Predicate.Parser.start[cty](FSharpFunc`2 lexer, LexBuffer`1 lexbuf) in D:\OneDrive_Privat\OneDrive\Uni_DTU\4.semester\02141 Datalogisk modellering F23\02141_workspace\02141-group-21-ef0e8\predicates\Parser.fs:line 1223
   at Predicate.Parse.parser@11-2.Invoke(LexBuffer`1 arg10@)
   at Predicate.Parse.parse(String src) in D:\OneDrive_Privat\OneDrive\Uni_DTU\4.semester\02141 Datalogisk modellering F23\02141_workspace\02141-group-21-ef0e8\predicates\Parse.fs:line 14)
   at ProgramVerification.analysis(String src, Unit input) in D:\OneDrive_Privat\OneDrive\Uni_DTU\4.semester\02141 Datalogisk modellering F23\02141_workspace\02141-group-21-ef0e8\ProgramVerification.fs:line 28
   at Program.main(String[] args) in D:\OneDrive_Privat\OneDrive\Uni_DTU\4.semester\02141 Datalogisk modellering F23\02141_workspace\02141-group-21-ef0e8\Program.fs:line 73
```

**Comment by SUIFENGSK** [comment]
No issue after all. Christoph clarified the correct way.
